---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/WellCompletion/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never # original value always ...if you keep always on starting your entries would be deleted
    hikari:
      maximum-pool-size: 1
